version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/site-al_coworking
permissions:
  - object: /home/ubuntu
    pattern: "site-al_coworking"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/site-al_coworking
    pattern: "*app*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/site-al_coworking
    pattern: "*s*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/site-al_coworking
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
  - object: /home/ubuntu/site-al_coworking
    pattern: "*writable*"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory
  - object: /home/ubuntu/site-al_coworking
    pattern: "*public*"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory
  - object: /home/ubuntu/site-al_coworking/writable
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/clear.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root